### ISSUE TITLE
Change Type of SplineDerivs in Jastrow/BsplineFunctor.h

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/miniqmc#132]
SplineDerivs in Jatrow/BsplineFunctor.h has std::vector<TinyVector<real_type, 3>> type.  Unless there is a compelling reason to keep it in this type, I suggest changing this to a pointer to an array, which is how all the other values, gradients, and laplacians are treated in this part of the code code.

**Comment by ye-luo** [comment]
I think there is no need to use pointers. If you access data() and cast it to real_type *, you will get contiguous 3N real_type data.

**Comment by lshulen** [comment]
Ye, our broader strategy is to try to abstract the data types as much as possible so that the kokkos branch can involve more minimal changes.  The std::vector<TinyVector<real_type, 3>> requires a slightly awkward syntax that the pointer to an array gets around.  What is gained by keeping the previous data type?

**Comment by ye-luo** [comment]
Directly using pointers is generally going backward. I'm not saying we can't change datatype. Indeed, we need to customize our own vector class with Kokkos, OpenMP enabled transparently. In the QMCPACK, we do use Vector class instead std::vector for the data with explict control needs.

**Comment by rcclay** [comment]
@ye-luo Sorry for my phrasing.  I agree that bare pointers are definitely not the best solution here.  The main advantage to using them here though is that it makes it consistent with the rest of the function calls in this object.

**Comment by ye-luo** [comment]
Since this is used only by evaluateDerivative which is needed for optimization. How about just remove all those related to WF optimization?

**Comment by prckent** [comment]
Good to reduce the amount of unnecessary code in the miniapp...
