### ISSUE TITLE
Rename WaveFunctionComponentBase to WaveFunctionComponent?

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/miniqmc#156]
I feel Base in WaveFunctionComponentBase is not necessary.
WaveFunctionComponent is obviously a base class and there is no confusion.

I'm trying to make names short.

**Comment by PDoakORNL** [comment]
I think in general this is a good sort of refactor. Filenames should be updated in tandem.

**Comment by mdewing** [comment]
I agree that the Base is not necessary in this case.

**Comment by prckent** [comment]
Agreed

**Comment by prckent** [comment]
We also need to do this in QMCPACK...
